apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '11'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"reddit-clone-app"},"name":"reddit-clone-deployment","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"reddit-clone-app","version":"1.0.0-36"}},"template":{"metadata":{"labels":{"app":"reddit-clone-app","version":"1.0.0-36"}},"spec":{"containers":[{"image":"reysylaj/reddit-clone-app:latest","name":"reddit-clone-app","ports":[{"containerPort":3000}],"resources":{"limits":{"cpu":"1"},"requests":{"cpu":"500m"}}}]}}}}
  creationTimestamp: '2024-05-03T21:18:14Z'
  generation: 10
  labels:
    app.kubernetes.io/instance: reddit-clone-app
  name: reddit-clone-deployment
  namespace: default
  resourceVersion: '140679'
  uid: 935ba30f-0fc4-45ef-b012-38f1bd9a4f2b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: reddit-clone-app
      version: "1.0.0-36"  # Add the version label here
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: reddit-clone-app
        version: 1.0.0-36
    spec:
      containers:
        - image: 'reysylaj/reddit-clone-app:latest'
          imagePullPolicy: IfNotPresent
          name: reddit-clone-app
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: '1'
            requests:
              cpu: 500m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  collisionCount: 1
  conditions:
    - lastTransitionTime: '2024-05-03T21:18:14Z'
      lastUpdateTime: '2024-05-04T10:00:34Z'
      message: >-
        ReplicaSet "reddit-clone-deployment-7dcb4979df" has successfully
        progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2024-05-04T10:00:48Z'
      lastUpdateTime: '2024-05-04T10:00:48Z'
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: 'False'
      type: Available
  observedGeneration: 10
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
